### ISSUE TITLE
Add checkbox besides subprimer-num to label non-crawlable URLs

### ISSUE THREAD

**Issue by sonalranjit** [edgi-govdata-archiving/eot-nomination-tool#20]
add a checkbox to the chrome extension (EDGI Harvard branch), directly to the right of the "sub-primer num". Label above could be called: "Not crawlable:" I've also just added an extra field in the google form.

**Comment by trinberg** [comment]
@titaniumbones and I just discussed the following:

App additions/changes:
- make the three current Agency Office Code integer fields required
- add an additional integer field (for **4 total**) in same row as the three current Agency Office Code integer fields
- for checkbox listed above, change label to "Contains Uncrawlable Info"
- change all fields so that they remain populated after a successful submission (the three current Agency Office Codes are cleared after submission in the current version)
- if possible (not necessary) increase total height of extension window a small amount so scrolling is not necessary

if you have any questions: please call/message, we'll be up late.

**Comment by titaniumbones** [comment]
Window height maxes out at 600px so can't be increased, but I massaged CSS so scrolling not necessary.  If @mi-lee or @sonalranjit wants to improve my bottom-of-the-barrel CSS  rules (lines 7-11) that would be great.  Committed and pushed to harvard-edgi in 74c8466481054c289a21f437cdacb112967bedb7

**Comment by trinberg** [comment]
copying over from slack:
@mattprice - it looks awesome! thanks so much. a few points:
- seems like uncrawlable checkbox is not working for me (i.e. it's not populating the google sheet) (edited)
- all 4 of the agency office codes are required, but perhaps we can make the last box optional
- can you change "uncrawlable data" --> "uncrawlable content" (approved in-person by @michellem @rlave)
otherwise, the extension looks great!

**Comment by titaniumbones** [comment]
Hmm, thought I'd fixed the checkbox problem but I'm having some trouble. checkboxes on google forms are ocmplicated objects, with a structure like this: 

```html
<div jsname="JNdkSc" role="group" aria-labelledby="i23" aria-describedby="i.desc.1108008172 i.err.1108008172 i.req.1108008172" class=""><div class="" jsname="MPu53c" jscontroller="GJQA8b" jsaction="JIbuQc:aj0Jcf" data-value="Non-crawlable"><div class="freebirdFormviewerViewItemsCheckboxChoice"><label class="docssharedWizToggleLabeledContainer freebirdFormviewerViewItemsCheckboxContainer"><div class="exportLabelWrapper"><div class="quantumWizTogglePapercheckboxEl docssharedWizToggleLabeledControl freebirdThemedCheckbox freebirdThemedCheckboxDarkerDisabled freebirdFormviewerViewItemsCheckboxControl isCheckedNext" jscontroller="EcW08c" jsaction="click:cOuCgd; mousedown:UX7yZ; mouseup:lbsD7e; mouseleave:JywGue; touchstart:p6p2H; touchmove:FwuNnf; touchend:yfqBxc(preventMouseEvents=true|preventDefault=true); touchcancel:JMtRjd; focus:AHmuwe; blur:O22p3e; keydown:I481le; contextmenu:mg9Pef" jsshadow="" jsname="FkQz1b" aria-label="Non-crawlable" tabindex="0" aria-describedby="  i26" role="checkbox" aria-checked="false"><div class="quantumWizTogglePapercheckboxInk exportInk"></div><div class="quantumWizTogglePapercheckboxInnerBox"></div><div class="quantumWizTogglePapercheckboxCheckMarkContainer"><div class="quantumWizTogglePapercheckboxCheckMark"><div class="quantumWizTogglePapercheckboxShort"></div><div class="quantumWizTogglePapercheckboxLong"></div></div></div></div><div class="docssharedWizToggleLabeledContent"><div class="docssharedWizToggleLabeledPrimaryText"><span dir="auto" class="docssharedWizToggleLabeledLabelText exportLabel freebirdFormviewerViewItemsCheckboxLabel">Non-crawlable</span></div></div></div></label></div><input name="entry.2059306163" jsname="ekGZBc" disabled="" type="hidden"></div></div>
```
I guess the best thing is to change the google form input back to a text field.  doing that now.

**Comment by titaniumbones** [comment]
fixed.  please test.

**Comment by titaniumbones** [comment]
updated existing chrome package.  No logos, sorry.  But all of this stuff should work. We can update the datarefuge repo later.

**Comment by trinberg** [comment]
looks like it's always "yes" now

if nothing else works - maybe you can make it an integer entry field (1 and 0).

**Comment by titaniumbones** [comment]
fixed in latest commit.  

@trinberg can you guys update the README, esp the "Usage" instructions -- I will copy/paste to the chrome extension.  This will break the workflow of people used to the old version, so we should explain how to find the agency/subagency/org/suborg numbers.

**Comment by trinberg** [comment]
ok - working on the README now

**Comment by titaniumbones** [comment]
README also merged (again, have lost track of & am now too busy/tired to find the commit #).
