### ISSUE TITLE
Integrate directly with archivers 2.0

### ISSUE THREAD

**Issue by b5** [edgi-govdata-archiving/eot-nomination-tool#75]
Hi team! I've been working on integrating the EOT tool output into archivers 2.0, just wanted to check to see if the behavior of adding identical urls is intended.

**Comment by titaniumbones** [comment]
hi @b5, do you mean "are we doing a dupe check" (no), or "are we purposely adding large numbers of duplicate urls via the extension (also no).  Am nhoping the 2nd is not something that's happening

As long as we use a spreadsheet backend, querying our storage medium for the URL will be difficult/slow. We already check if it's been archived by archive.org. At some point we should probalby rewrite the extension so that it integrates directly into archivers 2.0, yes? But probably we want to figure out the schope of future archiving events/activities a bit better first?

**Comment by titaniumbones** [comment]
A while back @sonalranjit was trying to move away from spreadsheets over to adding URL's directly archivers, but at the time it was a bit of a moving target, is it time to move over to arhcivers 2.0? If so, give some skeletal guidance, maybe we can do it tonight.

**Comment by sonalranjit** [comment]
@b5 would be too much to maintain if we just create a standlone db service for the extension submissions or submitting it to patchbay?

**Comment by sonalranjit** [comment]
api.archivers.space/v0/uncrawlables @mi-lee

**Comment by mi-lee** [comment]
Hi @b5, is there a way we can search to make sure the URL isn't a duplicate before we send it? Or are you managing the duplicates on the server?

**Comment by titaniumbones** [comment]
changed title to reflect new direction!

**Comment by danielballan** [comment]
This is safe to close, I think, as the _new_ new direction is to integrate with [walk](https://github.com/qri-io/walk) once it's ready.
